config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :restaurants
  resources :reserve_records

  root to: "welcome#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end


    
      # Define abilities for the passed in user here. For example:

      user ||= User.new # guest user (not logged in)

      if user.superadmin_role?
        can :manage, :all
        can :access, :rails_admin       # only allow admin users to access Rails Admin
        can :read, :dashboard         # allow access to dashboard
      end
      if user.supervisor_role?
        can :manage, Restaurant
        can :access, :rails_admin
        can :read, :dashboard         # allow access to dashboard
      end


    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/costumer.rb
class Costumer < ApplicationRecord
  has_many :reserve_records
  has_many :restaurants, through: :reserve_records
end

app/models/reserve_record.rb
class ReserveRecord < ApplicationRecord
  belongs_to :costumer
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reserve_records
  has_many :costumers, through: :reserve_records
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    restaurants_path
  end
end

app/controllers/costumers_controller.rb
class CostumersController < ApplicationController
  
end

app/controllers/reserve_records_controller.rb
class ReserveRecordsController < ApplicationController

  def new
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end
  def show
  end

  def new
    redirect_to rails_admin.new_path('restaurant')
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costumer_helper.rb
module CostumerHelper
end

app/helpers/costumers_helper.rb
module CostumersHelper
end

app/helpers/reserve_records_helper.rb
module ReserveRecordsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/index.html.erb
<!-- index.html.erb -->

<!DOCTYPE html>
<html lang="en">
		<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	 	<title>Home</title>
	 	<style type="text/css">
	 	</style>
	</head>
	<body>
		
		<h1>home</h1>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% unless flash.empty? %>
       <script type="text/javascript">
          <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
         toastr['<%= type %>']('<%= f[1] %>');
       <% end %>
       </script>
    <% end %>
  </body>
</html>

app/views/restaurants/index.html.erb
<!-- index.html.erb -->


	<body>
		<div class="rsr-title">
			<h1>RESTAURANTS</h1>
		</div>
		<% if user_signed_in? %>

		  <%= link_to('Edit User', edit_user_registration_path) %>
		  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
		  <% if current_user.supervisor_role? || current_user.superadmin_role?%>
		  	<%= link_to('Add Restaurant', new_restaurant_path) %>
		  <% end %>	      

		<% else %>

		  <%= link_to('Register', new_user_registration_path)  %>
		  <%= link_to('Login', new_user_session_path)  %>  

		<% end %>
		<div>
			<% if current_user.superadmin_role? || current_user.supervisor_role? %>
				<p>Visible only for superadmins and supervisors! </p>
			<% end %>
		</div>
		<div class="container">
			<div class="row">
				<% @restaurants.each do |restaurant|%>
					<div class="col-6 mb-3">
						<div class="card-group">
							<div class="card" >
							    <img src="https://picsum.photos/300/200?random=1" class="card-img-top" alt="...">
							    <div class="card-body">
									<h6 class="card-title"><%= restaurant.name %></h6>
									<p class="card-text mb-0">Address: </p>
									<p class="card-text"><%= restaurant.address %></p>
									<p class="card-text mb-0">Phone: </p>
									<p class="card-text"><%= restaurant.phone %></p>
									<%= link_to( "Reserve a meal!", new_reserve_record_path, :class => "btn rsr-btn")%>
							    </div>
							</div>
						</div>
					</div>
				<% end %>
			</div>
		</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>

app/views/welcome/index.html.erb
<!-- index.html.erb -->

<!DOCTYPE html>
<html lang="en">
		<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	 	<title>Home</title>
	 	<style type="text/css">
	 	</style>
	</head>
	<body>
		
		<div class="hp_title">
			<h1>HOME</h1>
		</div>
		<div class="user_nb">
			<% if current_user.nil? %>
				<%= link_to new_user_session_path, class: 'login-button' do %>Sign in<% end %>
			<% else %>
				<%= link_to restaurants_path, class: 'login-button' do %>Go see Restaurants<% end %>
				<%= link_to destroy_user_session_path, method: :delete do %>Log out<% end %>
			<% end %>		
		</div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>